CREATE SEQUENCE SEQ_CHAT_CONVERSATION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE CHAT_CONVERSATION (
    CHAT_CONVERSATION_ID NUMBER(19,0) NOT NULL,
    PARTICIPANT_A_USER_ID NUMBER(19,0) NOT NULL,
    PARTICIPANT_B_USER_ID NUMBER(19,0) NOT NULL,
    LAST_MESSAGE_AT TIMESTAMP(6),
    CREATED_AT TIMESTAMP(6) NOT NULL,
    UPDATED_AT TIMESTAMP(6) NOT NULL,
    CONSTRAINT PK_CHAT_CONV PRIMARY KEY (CHAT_CONVERSATION_ID),
    CONSTRAINT FK_CHAT_CONV_A FOREIGN KEY (PARTICIPANT_A_USER_ID) REFERENCES APP_USER (USER_ID),
    CONSTRAINT FK_CHAT_CONV_B FOREIGN KEY (PARTICIPANT_B_USER_ID) REFERENCES APP_USER (USER_ID),
    CONSTRAINT UK_CHAT_CONV_AB UNIQUE (PARTICIPANT_A_USER_ID, PARTICIPANT_B_USER_ID),
    CONSTRAINT CK_CHAT_CONV_AB CHECK (PARTICIPANT_A_USER_ID <> PARTICIPANT_B_USER_ID)
);

CREATE INDEX IX_CHAT_CONV_A ON CHAT_CONVERSATION (PARTICIPANT_A_USER_ID);
CREATE INDEX IX_CHAT_CONV_B ON CHAT_CONVERSATION (PARTICIPANT_B_USER_ID);
CREATE INDEX IX_CHAT_CONV_LM ON CHAT_CONVERSATION (LAST_MESSAGE_AT);

CREATE SEQUENCE SEQ_CHAT_MESSAGE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE CHAT_MESSAGE (
    CHAT_MESSAGE_ID NUMBER(19,0) NOT NULL,
    CHAT_CONVERSATION_ID NUMBER(19,0) NOT NULL,
    SENDER_USER_ID NUMBER(19,0) NOT NULL,
    CONTENT VARCHAR2(2000 CHAR) NOT NULL,
    READ_YN CHAR(1) DEFAULT 'N' NOT NULL,
    READ_AT TIMESTAMP(6),
    CREATED_AT TIMESTAMP(6) NOT NULL,
    UPDATED_AT TIMESTAMP(6) NOT NULL,
    CONSTRAINT PK_CHAT_MSG PRIMARY KEY (CHAT_MESSAGE_ID),
    CONSTRAINT FK_CHAT_MSG_CONV FOREIGN KEY (CHAT_CONVERSATION_ID) REFERENCES CHAT_CONVERSATION (CHAT_CONVERSATION_ID),
    CONSTRAINT FK_CHAT_MSG_SND FOREIGN KEY (SENDER_USER_ID) REFERENCES APP_USER (USER_ID),
    CONSTRAINT CK_CHAT_MSG_READ CHECK (READ_YN IN ('Y', 'N'))
);

CREATE INDEX IX_CHAT_MSG_CONV ON CHAT_MESSAGE (CHAT_CONVERSATION_ID);
CREATE INDEX IX_CHAT_MSG_SND ON CHAT_MESSAGE (SENDER_USER_ID);
CREATE INDEX IX_CHAT_MSG_UNRD ON CHAT_MESSAGE (CHAT_CONVERSATION_ID, READ_YN, SENDER_USER_ID);
CREATE INDEX IX_CHAT_MSG_CRT ON CHAT_MESSAGE (CREATED_AT);
