insert into PROJECT_TYPE_CODE (PROJECT_TYPE_CODE, PROJECT_TYPE_NAME, SORT_ORDER, ACTIVE_YN) values ('HOSPITAL_COMPANION', 'Hospital Companion', 1, 'Y');
insert into REGION_CODE (REGION_CODE, PARENT_REGION_CODE, REGION_NAME, REGION_LEVEL, ACTIVE_YN) values ('SEOUL_GANGNAM', null, 'Seoul Gangnam', 2, 'Y');
insert into REVIEW_TAG_CODE (REVIEW_TAG_CODE, REVIEW_TAG_NAME, SORT_ORDER, ACTIVE_YN) values ('KIND', 'Kind', 1, 'Y');
insert into REVIEW_TAG_CODE (REVIEW_TAG_CODE, REVIEW_TAG_NAME, SORT_ORDER, ACTIVE_YN) values ('PUNCTUAL', 'Punctual', 2, 'Y');
