-- 프로젝트 도메인 Oracle DDL 자산
CREATE SEQUENCE SEQ_PROJECT
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE PROJECT (
    PROJECT_ID NUMBER(19, 0) NOT NULL,
    OWNER_USER_ID NUMBER(19, 0) NOT NULL,
    PROJECT_TYPE_CODE VARCHAR2(30 CHAR) NOT NULL,
    SERVICE_REGION_CODE VARCHAR2(20 CHAR) NOT NULL,
    TITLE VARCHAR2(200 CHAR) NOT NULL,
    REQUESTED_START_AT TIMESTAMP(6) NOT NULL,
    REQUESTED_END_AT TIMESTAMP(6) NOT NULL,
    SERVICE_ADDRESS VARCHAR2(300 CHAR) NOT NULL,
    SERVICE_DETAIL_ADDRESS VARCHAR2(300 CHAR),
    REQUEST_DETAIL CLOB NOT NULL,
    STATUS_CODE VARCHAR2(20 CHAR) NOT NULL,
    ACCEPTED_AT TIMESTAMP(6),
    STARTED_AT TIMESTAMP(6),
    COMPLETED_AT TIMESTAMP(6),
    CANCELLED_AT TIMESTAMP(6),
    CANCELLED_REASON CLOB,
    CREATED_AT TIMESTAMP(6) NOT NULL,
    UPDATED_AT TIMESTAMP(6) NOT NULL,
    CONSTRAINT PK_PROJECT PRIMARY KEY (PROJECT_ID),
    CONSTRAINT FK_PRJ_OWNER FOREIGN KEY (OWNER_USER_ID) REFERENCES APP_USER (USER_ID),
    CONSTRAINT FK_PRJ_TYPE FOREIGN KEY (PROJECT_TYPE_CODE) REFERENCES PROJECT_TYPE_CODE (PROJECT_TYPE_CODE),
    CONSTRAINT FK_PRJ_REGION FOREIGN KEY (SERVICE_REGION_CODE) REFERENCES REGION_CODE (REGION_CODE),
    CONSTRAINT CK_PRJ_STATUS CHECK (STATUS_CODE IN ('REQUESTED', 'ACCEPTED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT CK_PRJ_TIME CHECK (REQUESTED_END_AT > REQUESTED_START_AT)
);

CREATE INDEX IDX_PRJ_OWNER_ST ON PROJECT (OWNER_USER_ID, STATUS_CODE);
CREATE INDEX IDX_PRJ_REGION ON PROJECT (SERVICE_REGION_CODE);
