DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'PORTFOLIO_FILE'
       AND COLUMN_NAME = 'FILE_DATA';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE PORTFOLIO_FILE ADD (FILE_DATA BLOB)';
    END IF;

    SELECT COUNT(*)
      INTO v_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'VERIFICATION_FILE'
       AND COLUMN_NAME = 'FILE_DATA';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE VERIFICATION_FILE ADD (FILE_DATA BLOB)';
    END IF;
END;
/
