-- ============================================================
-- 프로젝트 유형 코드 데이터
-- Oracle: MERGE INTO 방식 (중복 실행 안전)
-- ============================================================

MERGE INTO PROJECT_TYPE_CODE t
USING (SELECT 'HOSPITAL_COMPANION' CODE FROM DUAL) s ON (t.PROJECT_TYPE_CODE = s.CODE)
WHEN MATCHED THEN UPDATE SET
  PROJECT_TYPE_NAME = '병원 동행',
  SORT_ORDER        = 1,
  ACTIVE_YN         = 'Y'
WHEN NOT MATCHED THEN INSERT
  (PROJECT_TYPE_CODE, PROJECT_TYPE_NAME, SORT_ORDER, ACTIVE_YN)
VALUES
  ('HOSPITAL_COMPANION', '병원 동행', 1, 'Y');

MERGE INTO PROJECT_TYPE_CODE t
USING (SELECT 'OUTING_COMPANION' CODE FROM DUAL) s ON (t.PROJECT_TYPE_CODE = s.CODE)
WHEN MATCHED THEN UPDATE SET
  PROJECT_TYPE_NAME = '외출 동행',
  SORT_ORDER        = 2,
  ACTIVE_YN         = 'Y'
WHEN NOT MATCHED THEN INSERT
  (PROJECT_TYPE_CODE, PROJECT_TYPE_NAME, SORT_ORDER, ACTIVE_YN)
VALUES
  ('OUTING_COMPANION', '외출 동행', 2, 'Y');

MERGE INTO PROJECT_TYPE_CODE t
USING (SELECT 'GROCERY_SHOPPING' CODE FROM DUAL) s ON (t.PROJECT_TYPE_CODE = s.CODE)
WHEN MATCHED THEN UPDATE SET
  PROJECT_TYPE_NAME = '장보기 도움',
  SORT_ORDER        = 3,
  ACTIVE_YN         = 'Y'
WHEN NOT MATCHED THEN INSERT
  (PROJECT_TYPE_CODE, PROJECT_TYPE_NAME, SORT_ORDER, ACTIVE_YN)
VALUES
  ('GROCERY_SHOPPING', '장보기 도움', 3, 'Y');

MERGE INTO PROJECT_TYPE_CODE t
USING (SELECT 'DAILY_LIFE_SUPPORT' CODE FROM DUAL) s ON (t.PROJECT_TYPE_CODE = s.CODE)
WHEN MATCHED THEN UPDATE SET
  PROJECT_TYPE_NAME = '일상 생활 지원',
  SORT_ORDER        = 4,
  ACTIVE_YN         = 'Y'
WHEN NOT MATCHED THEN INSERT
  (PROJECT_TYPE_CODE, PROJECT_TYPE_NAME, SORT_ORDER, ACTIVE_YN)
VALUES
  ('DAILY_LIFE_SUPPORT', '일상 생활 지원', 4, 'Y');

MERGE INTO PROJECT_TYPE_CODE t
USING (SELECT 'NURSING_CARE' CODE FROM DUAL) s ON (t.PROJECT_TYPE_CODE = s.CODE)
WHEN MATCHED THEN UPDATE SET
  PROJECT_TYPE_NAME = '요양 보호',
  SORT_ORDER        = 5,
  ACTIVE_YN         = 'Y'
WHEN NOT MATCHED THEN INSERT
  (PROJECT_TYPE_CODE, PROJECT_TYPE_NAME, SORT_ORDER, ACTIVE_YN)
VALUES
  ('NURSING_CARE', '요양 보호', 5, 'Y');

COMMIT;
