-- ============================================================
-- 대한민국 지역 코드 초기 데이터
-- REGION_LEVEL 1 = 시/도 (대분류)
-- REGION_LEVEL 2 = 구/시/군 (중분류)
-- Oracle: MERGE INTO 방식 (중복 실행 안전)
-- ============================================================

-- ── 레벨 1: 시/도 ────────────────────────────────────────────

MERGE INTO REGION_CODE t USING (SELECT 'SEOUL' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('SEOUL',NULL,'서울특별시',1,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'BUSAN' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('BUSAN',NULL,'부산광역시',1,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'DAEGU' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('DAEGU',NULL,'대구광역시',1,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'INCHEON' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('INCHEON',NULL,'인천광역시',1,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GWANGJU' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GWANGJU',NULL,'광주광역시',1,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'DAEJEON' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('DAEJEON',NULL,'대전광역시',1,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'ULSAN' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('ULSAN',NULL,'울산광역시',1,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'SEJONG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('SEJONG',NULL,'세종특별자치시',1,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGGI' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGGI',NULL,'경기도',1,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GANGWON' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GANGWON',NULL,'강원특별자치도',1,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'CHUNGBUK' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('CHUNGBUK',NULL,'충청북도',1,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'CHUNGNAM' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('CHUNGNAM',NULL,'충청남도',1,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'JEONBUK' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('JEONBUK',NULL,'전북특별자치도',1,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'JEONNAM' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('JEONNAM',NULL,'전라남도',1,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGBUK' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGBUK',NULL,'경상북도',1,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGNAM' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGNAM',NULL,'경상남도',1,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'JEJU' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('JEJU',NULL,'제주특별자치도',1,'Y');


-- ── 레벨 2: 서울 25개 구 ─────────────────────────────────────

MERGE INTO REGION_CODE t USING (SELECT 'SEOUL_GANGNAM' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('SEOUL_GANGNAM','SEOUL','강남구',2,'Y');
WHEN MATCHED THEN UPDATE SET PARENT_REGION_CODE='SEOUL', REGION_LEVEL=2;

MERGE INTO REGION_CODE t USING (SELECT 'SEOUL_GANGDONG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('SEOUL_GANGDONG','SEOUL','강동구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'SEOUL_GANGBUK' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('SEOUL_GANGBUK','SEOUL','강북구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'SEOUL_GANGSEO' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('SEOUL_GANGSEO','SEOUL','강서구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'SEOUL_GWANAK' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('SEOUL_GWANAK','SEOUL','관악구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'SEOUL_GWANGJIN' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('SEOUL_GWANGJIN','SEOUL','광진구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'SEOUL_GURO' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('SEOUL_GURO','SEOUL','구로구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'SEOUL_GEUMCHEON' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('SEOUL_GEUMCHEON','SEOUL','금천구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'SEOUL_NOWON' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('SEOUL_NOWON','SEOUL','노원구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'SEOUL_DOBONG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('SEOUL_DOBONG','SEOUL','도봉구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'SEOUL_DONGDAEMUN' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('SEOUL_DONGDAEMUN','SEOUL','동대문구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'SEOUL_DONGJAK' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('SEOUL_DONGJAK','SEOUL','동작구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'SEOUL_MAPO' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('SEOUL_MAPO','SEOUL','마포구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'SEOUL_SEODAEMUN' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('SEOUL_SEODAEMUN','SEOUL','서대문구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'SEOUL_SEOCHO' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('SEOUL_SEOCHO','SEOUL','서초구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'SEOUL_SEONGDONG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('SEOUL_SEONGDONG','SEOUL','성동구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'SEOUL_SEONGBUK' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('SEOUL_SEONGBUK','SEOUL','성북구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'SEOUL_SONGPA' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('SEOUL_SONGPA','SEOUL','송파구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'SEOUL_YANGCHEON' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('SEOUL_YANGCHEON','SEOUL','양천구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'SEOUL_YEONGDEUNGPO' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('SEOUL_YEONGDEUNGPO','SEOUL','영등포구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'SEOUL_YONGSAN' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('SEOUL_YONGSAN','SEOUL','용산구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'SEOUL_EUNPYEONG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('SEOUL_EUNPYEONG','SEOUL','은평구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'SEOUL_JONGNO' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('SEOUL_JONGNO','SEOUL','종로구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'SEOUL_JUNG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('SEOUL_JUNG','SEOUL','중구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'SEOUL_JUNGNANG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('SEOUL_JUNGNANG','SEOUL','중랑구',2,'Y');


-- ── 레벨 2: 부산 16개 구/군 ──────────────────────────────────

MERGE INTO REGION_CODE t USING (SELECT 'BUSAN_GANGSEO' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('BUSAN_GANGSEO','BUSAN','강서구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'BUSAN_GEUMJEONG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('BUSAN_GEUMJEONG','BUSAN','금정구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'BUSAN_GIJANG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('BUSAN_GIJANG','BUSAN','기장군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'BUSAN_NAM' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('BUSAN_NAM','BUSAN','남구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'BUSAN_DONG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('BUSAN_DONG','BUSAN','동구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'BUSAN_DONGRAE' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('BUSAN_DONGRAE','BUSAN','동래구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'BUSAN_BUSANJIN' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('BUSAN_BUSANJIN','BUSAN','부산진구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'BUSAN_BUK' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('BUSAN_BUK','BUSAN','북구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'BUSAN_SASANG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('BUSAN_SASANG','BUSAN','사상구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'BUSAN_SAHA' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('BUSAN_SAHA','BUSAN','사하구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'BUSAN_SEO' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('BUSAN_SEO','BUSAN','서구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'BUSAN_SUYEONG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('BUSAN_SUYEONG','BUSAN','수영구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'BUSAN_YEONJE' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('BUSAN_YEONJE','BUSAN','연제구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'BUSAN_YEONGDO' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('BUSAN_YEONGDO','BUSAN','영도구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'BUSAN_JUNG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('BUSAN_JUNG','BUSAN','중구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'BUSAN_HAEUNDAE' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('BUSAN_HAEUNDAE','BUSAN','해운대구',2,'Y');


-- ── 레벨 2: 대구 8개 구/군 ───────────────────────────────────

MERGE INTO REGION_CODE t USING (SELECT 'DAEGU_NAM' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('DAEGU_NAM','DAEGU','남구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'DAEGU_DALSEO' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('DAEGU_DALSEO','DAEGU','달서구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'DAEGU_DALSEONG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('DAEGU_DALSEONG','DAEGU','달성군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'DAEGU_DONG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('DAEGU_DONG','DAEGU','동구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'DAEGU_BUK' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('DAEGU_BUK','DAEGU','북구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'DAEGU_SEO' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('DAEGU_SEO','DAEGU','서구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'DAEGU_SUSEONG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('DAEGU_SUSEONG','DAEGU','수성구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'DAEGU_JUNG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('DAEGU_JUNG','DAEGU','중구',2,'Y');


-- ── 레벨 2: 인천 10개 구/군 ──────────────────────────────────

MERGE INTO REGION_CODE t USING (SELECT 'INCHEON_GANGHWA' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('INCHEON_GANGHWA','INCHEON','강화군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'INCHEON_GYEYANG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('INCHEON_GYEYANG','INCHEON','계양구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'INCHEON_NAMDONG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('INCHEON_NAMDONG','INCHEON','남동구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'INCHEON_DONG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('INCHEON_DONG','INCHEON','동구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'INCHEON_MICHUHOL' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('INCHEON_MICHUHOL','INCHEON','미추홀구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'INCHEON_BUPYEONG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('INCHEON_BUPYEONG','INCHEON','부평구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'INCHEON_SEO' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('INCHEON_SEO','INCHEON','서구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'INCHEON_YEONSU' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('INCHEON_YEONSU','INCHEON','연수구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'INCHEON_ONGJIN' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('INCHEON_ONGJIN','INCHEON','옹진군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'INCHEON_JUNG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('INCHEON_JUNG','INCHEON','중구',2,'Y');


-- ── 레벨 2: 광주 5개 구 ──────────────────────────────────────

MERGE INTO REGION_CODE t USING (SELECT 'GWANGJU_GWANGSAN' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GWANGJU_GWANGSAN','GWANGJU','광산구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GWANGJU_NAM' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GWANGJU_NAM','GWANGJU','남구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GWANGJU_DONG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GWANGJU_DONG','GWANGJU','동구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GWANGJU_BUK' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GWANGJU_BUK','GWANGJU','북구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GWANGJU_SEO' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GWANGJU_SEO','GWANGJU','서구',2,'Y');


-- ── 레벨 2: 대전 5개 구 ──────────────────────────────────────

MERGE INTO REGION_CODE t USING (SELECT 'DAEJEON_DAEDEOK' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('DAEJEON_DAEDEOK','DAEJEON','대덕구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'DAEJEON_DONG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('DAEJEON_DONG','DAEJEON','동구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'DAEJEON_SEO' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('DAEJEON_SEO','DAEJEON','서구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'DAEJEON_YUSEONG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('DAEJEON_YUSEONG','DAEJEON','유성구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'DAEJEON_JUNG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('DAEJEON_JUNG','DAEJEON','중구',2,'Y');


-- ── 레벨 2: 울산 5개 구/군 ───────────────────────────────────

MERGE INTO REGION_CODE t USING (SELECT 'ULSAN_NAM' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('ULSAN_NAM','ULSAN','남구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'ULSAN_DONG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('ULSAN_DONG','ULSAN','동구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'ULSAN_BUK' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('ULSAN_BUK','ULSAN','북구',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'ULSAN_ULJU' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('ULSAN_ULJU','ULSAN','울주군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'ULSAN_JUNG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('ULSAN_JUNG','ULSAN','중구',2,'Y');


-- ── 레벨 2: 경기 31개 시/군 ──────────────────────────────────

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGGI_SUWON' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGGI_SUWON','GYEONGGI','수원시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGGI_SEONGNAM' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGGI_SEONGNAM','GYEONGGI','성남시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGGI_UIJEONGBU' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGGI_UIJEONGBU','GYEONGGI','의정부시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGGI_ANYANG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGGI_ANYANG','GYEONGGI','안양시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGGI_BUCHEON' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGGI_BUCHEON','GYEONGGI','부천시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGGI_GWANGMYEONG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGGI_GWANGMYEONG','GYEONGGI','광명시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGGI_PYEONGTAEK' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGGI_PYEONGTAEK','GYEONGGI','평택시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGGI_ANSAN' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGGI_ANSAN','GYEONGGI','안산시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGGI_GOYANG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGGI_GOYANG','GYEONGGI','고양시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGGI_NAMYANGJU' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGGI_NAMYANGJU','GYEONGGI','남양주시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGGI_OSAN' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGGI_OSAN','GYEONGGI','오산시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGGI_SIHEUNG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGGI_SIHEUNG','GYEONGGI','시흥시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGGI_GUNPO' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGGI_GUNPO','GYEONGGI','군포시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGGI_UIWANG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGGI_UIWANG','GYEONGGI','의왕시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGGI_HANAM' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGGI_HANAM','GYEONGGI','하남시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGGI_YONGIN' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGGI_YONGIN','GYEONGGI','용인시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGGI_PAJU' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGGI_PAJU','GYEONGGI','파주시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGGI_ICHEON' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGGI_ICHEON','GYEONGGI','이천시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGGI_ANSEONG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGGI_ANSEONG','GYEONGGI','안성시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGGI_GIMPO' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGGI_GIMPO','GYEONGGI','김포시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGGI_HWASEONG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGGI_HWASEONG','GYEONGGI','화성시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGGI_GWANGJU' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGGI_GWANGJU','GYEONGGI','광주시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGGI_YANGJU' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGGI_YANGJU','GYEONGGI','양주시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGGI_POCHEON' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGGI_POCHEON','GYEONGGI','포천시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGGI_YEOJU' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGGI_YEOJU','GYEONGGI','여주시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGGI_DONGDUCHEON' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGGI_DONGDUCHEON','GYEONGGI','동두천시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGGI_GWACHEON' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGGI_GWACHEON','GYEONGGI','과천시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGGI_GURI' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGGI_GURI','GYEONGGI','구리시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGGI_YEONCHEON' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGGI_YEONCHEON','GYEONGGI','연천군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGGI_GAPYEONG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGGI_GAPYEONG','GYEONGGI','가평군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGGI_YANGPYEONG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGGI_YANGPYEONG','GYEONGGI','양평군',2,'Y');


-- ── 레벨 2: 강원 18개 시/군 ──────────────────────────────────

MERGE INTO REGION_CODE t USING (SELECT 'GANGWON_CHUNCHEON' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GANGWON_CHUNCHEON','GANGWON','춘천시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GANGWON_WONJU' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GANGWON_WONJU','GANGWON','원주시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GANGWON_GANGNEUNG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GANGWON_GANGNEUNG','GANGWON','강릉시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GANGWON_DONGHAE' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GANGWON_DONGHAE','GANGWON','동해시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GANGWON_TAEBAEK' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GANGWON_TAEBAEK','GANGWON','태백시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GANGWON_SOKCHO' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GANGWON_SOKCHO','GANGWON','속초시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GANGWON_SAMCHEOK' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GANGWON_SAMCHEOK','GANGWON','삼척시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GANGWON_HONGCHEON' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GANGWON_HONGCHEON','GANGWON','홍천군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GANGWON_HOENGSEONG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GANGWON_HOENGSEONG','GANGWON','횡성군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GANGWON_YEONGWOL' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GANGWON_YEONGWOL','GANGWON','영월군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GANGWON_PYEONGCHANG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GANGWON_PYEONGCHANG','GANGWON','평창군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GANGWON_JEONGSEON' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GANGWON_JEONGSEON','GANGWON','정선군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GANGWON_CHEORWON' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GANGWON_CHEORWON','GANGWON','철원군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GANGWON_HWACHEON' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GANGWON_HWACHEON','GANGWON','화천군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GANGWON_YANGGU' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GANGWON_YANGGU','GANGWON','양구군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GANGWON_INJE' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GANGWON_INJE','GANGWON','인제군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GANGWON_GOSEONG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GANGWON_GOSEONG','GANGWON','고성군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GANGWON_YANGYANG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GANGWON_YANGYANG','GANGWON','양양군',2,'Y');


-- ── 레벨 2: 충청북도 11개 시/군 ──────────────────────────────

MERGE INTO REGION_CODE t USING (SELECT 'CHUNGBUK_CHEONGJU' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('CHUNGBUK_CHEONGJU','CHUNGBUK','청주시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'CHUNGBUK_CHUNGJU' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('CHUNGBUK_CHUNGJU','CHUNGBUK','충주시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'CHUNGBUK_JECHEON' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('CHUNGBUK_JECHEON','CHUNGBUK','제천시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'CHUNGBUK_BOEUN' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('CHUNGBUK_BOEUN','CHUNGBUK','보은군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'CHUNGBUK_OKCHEON' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('CHUNGBUK_OKCHEON','CHUNGBUK','옥천군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'CHUNGBUK_YEONGDONG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('CHUNGBUK_YEONGDONG','CHUNGBUK','영동군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'CHUNGBUK_JEUNGPYEONG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('CHUNGBUK_JEUNGPYEONG','CHUNGBUK','증평군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'CHUNGBUK_JINCHEON' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('CHUNGBUK_JINCHEON','CHUNGBUK','진천군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'CHUNGBUK_GOESAN' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('CHUNGBUK_GOESAN','CHUNGBUK','괴산군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'CHUNGBUK_EUMSEONG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('CHUNGBUK_EUMSEONG','CHUNGBUK','음성군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'CHUNGBUK_DANYANG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('CHUNGBUK_DANYANG','CHUNGBUK','단양군',2,'Y');


-- ── 레벨 2: 충청남도 15개 시/군 ──────────────────────────────

MERGE INTO REGION_CODE t USING (SELECT 'CHUNGNAM_CHEONAN' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('CHUNGNAM_CHEONAN','CHUNGNAM','천안시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'CHUNGNAM_GONGJU' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('CHUNGNAM_GONGJU','CHUNGNAM','공주시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'CHUNGNAM_BORYEONG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('CHUNGNAM_BORYEONG','CHUNGNAM','보령시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'CHUNGNAM_ASAN' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('CHUNGNAM_ASAN','CHUNGNAM','아산시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'CHUNGNAM_SEOSAN' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('CHUNGNAM_SEOSAN','CHUNGNAM','서산시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'CHUNGNAM_NONSAN' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('CHUNGNAM_NONSAN','CHUNGNAM','논산시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'CHUNGNAM_GYERYONG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('CHUNGNAM_GYERYONG','CHUNGNAM','계룡시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'CHUNGNAM_DANGJIN' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('CHUNGNAM_DANGJIN','CHUNGNAM','당진시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'CHUNGNAM_GEUMSAN' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('CHUNGNAM_GEUMSAN','CHUNGNAM','금산군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'CHUNGNAM_BUYEO' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('CHUNGNAM_BUYEO','CHUNGNAM','부여군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'CHUNGNAM_SEOCHEON' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('CHUNGNAM_SEOCHEON','CHUNGNAM','서천군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'CHUNGNAM_CHEONGYANG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('CHUNGNAM_CHEONGYANG','CHUNGNAM','청양군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'CHUNGNAM_HONGSEONG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('CHUNGNAM_HONGSEONG','CHUNGNAM','홍성군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'CHUNGNAM_YESAN' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('CHUNGNAM_YESAN','CHUNGNAM','예산군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'CHUNGNAM_TAEAN' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('CHUNGNAM_TAEAN','CHUNGNAM','태안군',2,'Y');


-- ── 레벨 2: 전라북도 14개 시/군 ──────────────────────────────

MERGE INTO REGION_CODE t USING (SELECT 'JEONBUK_JEONJU' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('JEONBUK_JEONJU','JEONBUK','전주시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'JEONBUK_GUNSAN' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('JEONBUK_GUNSAN','JEONBUK','군산시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'JEONBUK_IKSAN' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('JEONBUK_IKSAN','JEONBUK','익산시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'JEONBUK_JEONGEUP' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('JEONBUK_JEONGEUP','JEONBUK','정읍시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'JEONBUK_NAMWON' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('JEONBUK_NAMWON','JEONBUK','남원시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'JEONBUK_GIMJE' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('JEONBUK_GIMJE','JEONBUK','김제시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'JEONBUK_WANJU' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('JEONBUK_WANJU','JEONBUK','완주군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'JEONBUK_JINAN' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('JEONBUK_JINAN','JEONBUK','진안군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'JEONBUK_MUJU' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('JEONBUK_MUJU','JEONBUK','무주군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'JEONBUK_JANGSU' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('JEONBUK_JANGSU','JEONBUK','장수군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'JEONBUK_IMSIL' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('JEONBUK_IMSIL','JEONBUK','임실군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'JEONBUK_SUNCHANG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('JEONBUK_SUNCHANG','JEONBUK','순창군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'JEONBUK_GOCHANG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('JEONBUK_GOCHANG','JEONBUK','고창군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'JEONBUK_BUAN' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('JEONBUK_BUAN','JEONBUK','부안군',2,'Y');


-- ── 레벨 2: 전라남도 22개 시/군 ──────────────────────────────

MERGE INTO REGION_CODE t USING (SELECT 'JEONNAM_MOKPO' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('JEONNAM_MOKPO','JEONNAM','목포시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'JEONNAM_YEOSU' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('JEONNAM_YEOSU','JEONNAM','여수시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'JEONNAM_SUNCHEON' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('JEONNAM_SUNCHEON','JEONNAM','순천시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'JEONNAM_NAJU' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('JEONNAM_NAJU','JEONNAM','나주시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'JEONNAM_GWANGYANG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('JEONNAM_GWANGYANG','JEONNAM','광양시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'JEONNAM_DAMYANG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('JEONNAM_DAMYANG','JEONNAM','담양군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'JEONNAM_GOKSEONG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('JEONNAM_GOKSEONG','JEONNAM','곡성군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'JEONNAM_GURYE' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('JEONNAM_GURYE','JEONNAM','구례군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'JEONNAM_GOHEUNG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('JEONNAM_GOHEUNG','JEONNAM','고흥군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'JEONNAM_BOSEONG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('JEONNAM_BOSEONG','JEONNAM','보성군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'JEONNAM_HWASUN' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('JEONNAM_HWASUN','JEONNAM','화순군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'JEONNAM_JANGHEUNG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('JEONNAM_JANGHEUNG','JEONNAM','장흥군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'JEONNAM_GANGJIN' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('JEONNAM_GANGJIN','JEONNAM','강진군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'JEONNAM_HAENAM' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('JEONNAM_HAENAM','JEONNAM','해남군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'JEONNAM_YEONGAM' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('JEONNAM_YEONGAM','JEONNAM','영암군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'JEONNAM_MUAN' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('JEONNAM_MUAN','JEONNAM','무안군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'JEONNAM_HAMPYEONG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('JEONNAM_HAMPYEONG','JEONNAM','함평군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'JEONNAM_YEONGGWANG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('JEONNAM_YEONGGWANG','JEONNAM','영광군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'JEONNAM_JANGSEONG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('JEONNAM_JANGSEONG','JEONNAM','장성군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'JEONNAM_WANDO' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('JEONNAM_WANDO','JEONNAM','완도군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'JEONNAM_JINDO' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('JEONNAM_JINDO','JEONNAM','진도군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'JEONNAM_SINAN' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('JEONNAM_SINAN','JEONNAM','신안군',2,'Y');


-- ── 레벨 2: 경상북도 23개 시/군 ──────────────────────────────

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGBUK_POHANG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGBUK_POHANG','GYEONGBUK','포항시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGBUK_GYEONGJU' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGBUK_GYEONGJU','GYEONGBUK','경주시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGBUK_GIMCHEON' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGBUK_GIMCHEON','GYEONGBUK','김천시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGBUK_ANDONG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGBUK_ANDONG','GYEONGBUK','안동시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGBUK_GUMI' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGBUK_GUMI','GYEONGBUK','구미시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGBUK_YEONGJU' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGBUK_YEONGJU','GYEONGBUK','영주시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGBUK_YEONGCHEON' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGBUK_YEONGCHEON','GYEONGBUK','영천시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGBUK_SANGJU' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGBUK_SANGJU','GYEONGBUK','상주시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGBUK_MUNGYEONG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGBUK_MUNGYEONG','GYEONGBUK','문경시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGBUK_GYEONGSAN' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGBUK_GYEONGSAN','GYEONGBUK','경산시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGBUK_GUNWI' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGBUK_GUNWI','GYEONGBUK','군위군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGBUK_UISEONG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGBUK_UISEONG','GYEONGBUK','의성군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGBUK_CHEONGSONG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGBUK_CHEONGSONG','GYEONGBUK','청송군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGBUK_YEONGYANG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGBUK_YEONGYANG','GYEONGBUK','영양군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGBUK_YEONGDEOK' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGBUK_YEONGDEOK','GYEONGBUK','영덕군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGBUK_CHEONGDO' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGBUK_CHEONGDO','GYEONGBUK','청도군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGBUK_GORYEONG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGBUK_GORYEONG','GYEONGBUK','고령군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGBUK_SEONGJU' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGBUK_SEONGJU','GYEONGBUK','성주군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGBUK_CHILGOK' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGBUK_CHILGOK','GYEONGBUK','칠곡군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGBUK_YECHEON' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGBUK_YECHEON','GYEONGBUK','예천군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGBUK_BONGHWA' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGBUK_BONGHWA','GYEONGBUK','봉화군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGBUK_ULJIN' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGBUK_ULJIN','GYEONGBUK','울진군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGBUK_ULLEUNG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGBUK_ULLEUNG','GYEONGBUK','울릉군',2,'Y');


-- ── 레벨 2: 경상남도 18개 시/군 ──────────────────────────────

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGNAM_CHANGWON' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGNAM_CHANGWON','GYEONGNAM','창원시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGNAM_JINJU' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGNAM_JINJU','GYEONGNAM','진주시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGNAM_TONGYEONG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGNAM_TONGYEONG','GYEONGNAM','통영시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGNAM_SACHEON' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGNAM_SACHEON','GYEONGNAM','사천시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGNAM_GIMHAE' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGNAM_GIMHAE','GYEONGNAM','김해시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGNAM_MIRYANG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGNAM_MIRYANG','GYEONGNAM','밀양시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGNAM_GEOJE' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGNAM_GEOJE','GYEONGNAM','거제시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGNAM_YANGSAN' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGNAM_YANGSAN','GYEONGNAM','양산시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGNAM_UIRYEONG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGNAM_UIRYEONG','GYEONGNAM','의령군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGNAM_HAMAN' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGNAM_HAMAN','GYEONGNAM','함안군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGNAM_CHANGNYEONG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGNAM_CHANGNYEONG','GYEONGNAM','창녕군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGNAM_GOSEONG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGNAM_GOSEONG','GYEONGNAM','고성군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGNAM_NAMHAE' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGNAM_NAMHAE','GYEONGNAM','남해군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGNAM_HADONG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGNAM_HADONG','GYEONGNAM','하동군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGNAM_SANCHEONG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGNAM_SANCHEONG','GYEONGNAM','산청군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGNAM_HAMYANG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGNAM_HAMYANG','GYEONGNAM','함양군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGNAM_GEOCHANG' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGNAM_GEOCHANG','GYEONGNAM','거창군',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'GYEONGNAM_HAPCHEON' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('GYEONGNAM_HAPCHEON','GYEONGNAM','합천군',2,'Y');


-- ── 레벨 2: 제주 2개 시 ──────────────────────────────────────

MERGE INTO REGION_CODE t USING (SELECT 'JEJU_JEJU' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('JEJU_JEJU','JEJU','제주시',2,'Y');

MERGE INTO REGION_CODE t USING (SELECT 'JEJU_SEOGWIPO' CODE FROM DUAL) s ON (t.REGION_CODE=s.CODE)
WHEN NOT MATCHED THEN INSERT (REGION_CODE,PARENT_REGION_CODE,REGION_NAME,REGION_LEVEL,ACTIVE_YN) VALUES ('JEJU_SEOGWIPO','JEJU','서귀포시',2,'Y');


COMMIT;
-- 총 17개 시/도 + 250개 구/시/군 = 267개 레코드
