-- ============================================================
-- 가능 시간대 코드 데이터 (3분류: 오전/오후/저녁)
-- Oracle: MERGE INTO 방식 (중복 실행 안전)
-- MORNING  : 09:00 ~ 12:00 (540 ~ 720분)
-- AFTERNOON: 12:00 ~ 17:00 (720 ~ 1020분)
-- EVENING  : 17:00 ~ 21:00 (1020 ~ 1260분)
-- ============================================================

MERGE INTO AVAILABLE_TIME_SLOT_CODE t
USING (SELECT 'MORNING' CODE FROM DUAL) s ON (t.TIME_SLOT_CODE = s.CODE)
WHEN MATCHED THEN UPDATE SET
  TIME_SLOT_NAME = '오전 (09:00~12:00)',
  START_MINUTE   = 540,
  END_MINUTE     = 720,
  SORT_ORDER     = 1,
  ACTIVE_YN      = 'Y'
WHEN NOT MATCHED THEN INSERT
  (TIME_SLOT_CODE, TIME_SLOT_NAME, START_MINUTE, END_MINUTE, SORT_ORDER, ACTIVE_YN)
VALUES
  ('MORNING', '오전 (09:00~12:00)', 540, 720, 1, 'Y');

MERGE INTO AVAILABLE_TIME_SLOT_CODE t
USING (SELECT 'AFTERNOON' CODE FROM DUAL) s ON (t.TIME_SLOT_CODE = s.CODE)
WHEN MATCHED THEN UPDATE SET
  TIME_SLOT_NAME = '오후 (12:00~17:00)',
  START_MINUTE   = 720,
  END_MINUTE     = 1020,
  SORT_ORDER     = 2,
  ACTIVE_YN      = 'Y'
WHEN NOT MATCHED THEN INSERT
  (TIME_SLOT_CODE, TIME_SLOT_NAME, START_MINUTE, END_MINUTE, SORT_ORDER, ACTIVE_YN)
VALUES
  ('AFTERNOON', '오후 (12:00~17:00)', 720, 1020, 2, 'Y');

MERGE INTO AVAILABLE_TIME_SLOT_CODE t
USING (SELECT 'EVENING' CODE FROM DUAL) s ON (t.TIME_SLOT_CODE = s.CODE)
WHEN MATCHED THEN UPDATE SET
  TIME_SLOT_NAME = '저녁 (17:00~21:00)',
  START_MINUTE   = 1020,
  END_MINUTE     = 1260,
  SORT_ORDER     = 3,
  ACTIVE_YN      = 'Y'
WHEN NOT MATCHED THEN INSERT
  (TIME_SLOT_CODE, TIME_SLOT_NAME, START_MINUTE, END_MINUTE, SORT_ORDER, ACTIVE_YN)
VALUES
  ('EVENING', '저녁 (17:00~21:00)', 1020, 1260, 3, 'Y');

COMMIT;
